---

- name: Hello World Msg
  # connection: local
  gather_facts: false
  hosts: homelab
  tasks:
    - name: Print hello world using debug
      debug:
        msg: "Debug Hello World"
    - name: Echo hello world from a shell
      shell: echo "Hello World"
    - name: Create a test file
      copy:
        dest: "~/testfile"
        content: |
          this is some hello world test
    - name: Create a test file that requires permissions
      become: true
      copy:
        dest: "/testfile"
        content: |
          this is a file tha requires root permissions \n